all:
  children: 
    linux:
      hosts:
        swarm-manager:
          ansible_ssh_host: '5.23.52.108'
          ansible_ssh_user: root
          ansible_ssh_timeout:  60
          ansible_ssh_private_key_file: ./ssh/key
        
        swarm-worker:
          ansible_ssh_host: '5.23.52.108'
          ansible_ssh_user: root
          ansible_ssh_timeout:  60
          ansible_ssh_private_key_file: ./ssh/key
          
            

                          

