version: '3.9'
services:
  
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      #placement:
          #constraints:
            #- "node.labels.type==backend"
      restart_policy:
          condition: on-failure
    secrets:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    
    networks:
      - net
  

  app:
    image: app
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      #placement:
          #constraints:
            #- "node.labels.type==backend"
      restart_policy:
          condition: on-failure
    networks:
      - net

secrets:
      nginx-config:
        file: /var/www/app/nginx.conf
        name: nginx-config-v8
  
networks:
  net:
    #ipam:
    #  config:
    #    - subnet: 2001:3200:3200::/64