---
- name: Install yum-utils
  yum:
    state: present
    update_cache: yes
    name:
      - yum-utils 
      - epel-release

  
- name: Uninstall old versions
  yum:
    state: removed
    update_cache: yes
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine 


- name: add docker repo
  ansible.builtin.command: 
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo



- name: Install docker
  yum:
    state: latest
    update_cache: yes
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Copy daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    #mode: '0644'
    backup: true

- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started

- name: Install pip docker
  ansible.builtin.pip:
    name: 
      - bottle
      - jsondiff
      - pyyaml

